# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e1683b5916371addee679b738e111eee36edfac80c9290a094dab86c1ca61417d7b629021027ccddab20be8d1ebf01f1879c840bf6877a7ba3793b47b16733

test:
  secret_key_base: e900457575f0db787a8f3062d6a3115b164c47ce80703759c693c45c07e45c8cf64dc3999cea6457c3ad2a3f08735910fc534bd705b47e7406f7ba16698f35ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
